var locales = {
    promptDelete: '确定要删除选中项?',
    promptChecked:'请勾选项目！',
    promptNullValue: '请输入关键词！',
    validateName: '请输入节目名称！',
    validateRq: '只能输入中文，英文，数字！',
    validateEq: '请选择设备型号！',
    validateLable: '请输入节目标签！',
    validateRes: '请选择分辨率！',
    validateWidth: '请输入自定义宽！' ,
    validateHeight: '请输入自定义高！' ,
    newProgram: '新建节目' ,
    editProgram: '修改节目' ,
    auditState: '审核状态：'  ,
    eqModal: '设备型号：'  ,
    updateMan: '更新人：'  ,
    isCommonState: '公开状态：'  ,
    updateTime: '更新时间：'  ,
    dateMoment: '开始时间必须在结束时间之前！'  ,
};